title: Trey O. Phelps
description: ESIIL Advanced Intern from OLC
![GitHub Selfie](C:\Users\student\Pictures\Camera Roll\github_selfie.png")
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme



# logo: img/github_selfie
